# Generated by Django 5.2.8 on 2026-05-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='starting_point',
            field=models.CharField(default='Delhi', max_length=200),
        ),
    ]
